# branches to build
branches:
  # whitelist
  only:
    - master

environment:
  PROJ: "c:/projects/empty-proj"

platform:
  - x86
  - x64

configuration:
  - Debug
  - Release

build:
  # path to Visual Studio solution or project
  project: c:/projects/empty-proj/build/check_on_install.vcxproj

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd /d %PROJ%
  - mkdir build
  - cd build
  - cmd: if "%platform%"=="x86" cmake -G"Visual Studio 12"  ..
  - cmd: if "%platform%"=="x64" cmake -G"Visual Studio 12 Win64" ..
