#!/bin/bash

projname=$(basename $(cd "$(dirname "$0")"; pwd))
artname="${projname}_${BTYPE}_${TRAVIS_OS_NAME}_${CC}"

tar -czf - install/* | uuencode "$artname.tar.gz" | mail -r "travisbuild@travis-ci.org" -s "$artname" akalsi.work@gmail.com <<< "$artname"
