#!/bin/bash

# prepare linux env
if [ ${TRAVIS_OS_NAME} = "linux" ]; then
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    sudo apt-get update -qq
    if [ ${CXX} = "g++" ]; then
        sudo apt-get install -y gcc-4.8 g++-4.8 lcov
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    fi
fi

# prepare mac env
if [ ${TRAVIS_OS_NAME} = "osx" ]; then
    if [ ${CC} = "gcc" ]; then
        export CXX="g++-4.8" && export CC="gcc-4.8"
        brew install lcov
    fi
fi

# use CMake 3.2
cd /tmp && curl http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz | tar -xzf -
cd cmake-3.2.2
(./bootstrap && sudo make install -j6) &> /dev/null
