#!/bin/bash

set -e

echo "[TRAVIS_SETUP] Preparing build tools..."

# prepare linux env
if [ ${TRAVIS_OS_NAME} = "linux" ]; then
    (sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test) &> /dev/null
    (sudo apt-get update -qq) &> /dev/null
    (sudo apt-get install -y lcov) &> /dev/null
    if [ ${CXX} = "g++" ]; then
        (sudo apt-get install -y gcc-4.8 g++-4.8) &> /dev/null
    fi
    (sudo apt-get install -y graphviz doxygen) &> /dev/null
fi

# prepare mac env
if [ ${TRAVIS_OS_NAME} = "osx" ]; then
    (brew install lcov) &> /dev/null
    (brew install graphviz) &> /dev/null
    (brew install doxygen) &> /dev/null
fi

# use CMake 3.2
echo "[TRAVIS_SETUP] Installing CMake 3.2..."
cd /tmp
(curl https://cmake.org/files/v3.2/cmake-3.2.2.tar.gz | tar -xzf -) &> /dev/null
cd cmake-3.2.2
(./bootstrap && sudo make install -j8) &> /dev/null
