#!/bin/bash

tools_dir=`dirname $0`
PARAMS=""
for PARAM in "$@"
do
  PARAMS="${PARAMS} \"${PARAM}\""
done

bash -c "${tools_dir}/regen \"${PARAMS}\""
cmake --build ${tools_dir}/../build --target check --config $1
