#!/bin/bash

tools_dir=$(cd "$(dirname "$0")"; pwd)
proj_dir=`dirname ${tools_dir}`

olddir=`pwd`

if [ $# -ne 1 ];
then
  echo "Usage:"
  echo "  createtest name_of_test"
  exit 1
fi

fn=`basename $1`
d=`dirname $1`

if [ $d = "." ];
then
  d=""
  dfull=""
else
  dfull="$d/"
fi

mkdir -p ${proj_dir}/test/${d}

extension="${fn##*.}"

if [ $extension = "c" ];
then
    echo \
"/**
 * \file ${fn}
 * \date `date \"+%b %d, %Y\"`
 */

#include \"unittest.h\"

TEST_FUNC( no_op )
{
    TEST_TRUE( 1 );
}

void SetupTests(void)
{
    REG_TEST( no_op );
}" > ${proj_dir}/test/${dfull}${fn}
else
    echo \
"/**
 * \file ${fn}
 * \date `date \"+%b %d, %Y\"`
 */

#include \"unittest.hpp\"

CPP_TEST( no_op )
{

}" > ${proj_dir}/test/${dfull}${fn}
fi

echo \
"
add_test_exe    (${fn%.*} ${dfull}${fn})
test_link_libs  (${fn%.*} )
create_test     (${fn%.*})" >> ${proj_dir}/test/CMakeLists.txt
