#!/bin/bash

tools_dir=$(cd "$(dirname "$0")"; pwd)
proj_dir=`dirname ${tools_dir}`

cd ${proj_dir}

PARAMS=""
for PARAM in "$@"
do
  PARAMS="${PARAMS} \"${PARAM}\""
done

bash -c "echo y | ${tools_dir}/regen ${PARAMS}"
export VERBOSE=1

# do doc build
cmake --build ${tools_dir}/../build --target doc --config $1
cp -rf ${proj_dir}/build/doc/html/* ${proj_dir}/doc/html

# remove install
rm -fr ${proj_dir}/install

# do install
cmake --build ${tools_dir}/../build --target install --config $1
