#!/bin/bash

tools_dir=$(cd "$(dirname "$0")"; pwd)
proj_dir=`dirname ${tools_dir}`

cd ${proj_dir}

PARAMS=""
for PARAM in "$@"
do
  PARAMS="${PARAMS} \"${PARAM}\""
done

export INSTALL_BASE_DIR="${tools_dir}/../install"

bash -c "echo y | ${tools_dir}/regen ${PARAMS}"
export VERBOSE=1

# do install
cmake --build ${tools_dir}/../build --target install --config $1
