#!/bin/bash

tools_dir=$(cd "$(dirname "$0")"; pwd)
proj_dir=`dirname ${tools_dir}`

cd ${proj_dir}

${tools_dir}/install "$@"

cmake --build ${tools_dir}/../build --target check_on_install --config $1
